#!/usr/local/ActivePerl/bin/perl
#
#
#

use strict;
use Getopt::Long;
use Data::Dumper;


my $USAGE=<<USAGE;

  * alnfilter *

   given a stream of blast m8 format tab-delimited data keeps
   only lines that have alignment length >= 50 (by default)

   options:

    -l, -length       whatever value you want for the alignment length
    -h, -help         display this help


   usage:

   cat blastresult.txt | alnfilter -l 100

   # BLAST -m 8 Fields: 
   0    1   Query id, 
   1    2   Subject id, 
   2    3   % identity, 
   3    4   alignment length, 
   4    5   mismatches, 
   5    6   gap openings, 
   6    7   q. start, 
   7    8   q. end, 
   8    9   s. start, 
   9    10  s. end, 
   10   11  e-value, 
   11   12  bit score 

  see also:

      idfilter, evfilter 

   - for getting this help -
   
    alnfilter -h
    alnfilter --help

USAGE

my ($length,$help,$format);
$length = 50;

my   $result = GetOptions ("l|length=f"    => \$length,      
			   "h|help"        => \$help
			   );     # flag

die $USAGE if $help;


while (my $line = <>){
	my @array=split(/\t/,$line);
	next if $array[3] < $length;
	print $line;
}


